---
version: '0.2'

import: []

ignorePaths: []
dictionaryDefinitions: []

dictionaries:
  - en_US
  - softwareTerms
  - bash

words:
  - Georg
  - Lauterbach

  - recognised
  - unrecognised

ignoreWords:
  - autocd
  - blesh
  - binutils
  - btop
  - bufread
  - checkwinsize
  - clippy
  - dircolors
  - dirtrim
  - dysk
  - everforest
  - evergruv
  - flyline
  - georglauterbach
  - getline
  - gitui
  - gsettings
  - gsub
  - herdr
  - histappend
  - ignoreboth
  - libflyline
  - manroffopt
  - perfmon
  - reqwest
  - rustdoc
  - rustls
  - setcap
  - sharkdp
  - sigusr2
  - softprops
  - trixie
  - xattrs
  - yazi
  - zizmor
  - zstd
