---
ignoreWords:
  - COLORFGBG
  - ISIG

  - autocd
  - checkwinsize
  - dircolors
  - dirtrim
  - dysk
  - getline
  - gsub
  - histappend
  - icanon
  - ignoreboth
  - manroffopt
  - perfmon
  - setcap
  - sigusr
  - stty
