---
version: '0.2'

import: []

ignorePaths: []
dictionaryDefinitions: []

dictionaries:
  - en_US
  - softwareTerms
  - bash

words:
  - Georg
  - Lauterbach

  - foldables
  - keepalive
  - recognised
  - unrecognised
  - worktree
  - worktrees

ignoreWords:
  - autocd
  - blesh
  - binutils
  - btop
  - bufread
  - catppuccin
  - checkwinsize
  - clippy
  - dircolors
  - dirtrim
  - dysk
  - everforest
  - evergruv
  - flyline
  - georglauterbach
  - getline
  - ghostty
  - gitui
  - gsettings
  - gsub
  - herdr
  - histappend
  - ignoreboth
  - kanagawa
  - kimi
  - kiro
  - libflyline
  - manroffopt
  - nord
  - opencode
  - perfmon
  - qoder
  - qodercli
  - reflog
  - reqwest
  - rrggbb
  - rustdoc
  - rustls
  - setcap
  - sharkdp
  - sigusr2
  - softprops
  - trixie
  - xattrs
  - yazi
  - zizmor
  - zstd
