---
version: '0.2'

import: []

ignorePaths: []
dictionaryDefinitions: []

dictionaries:
  - en_US
  - softwareTerms
  - bash

words:
  - Georg
  - Lauterbach

  - recognised
  - unrecognised

ignoreWords:
  - atuin
  - atuinsh
  - blesh
  - binutils
  - btop
  - bufread
  - clippy
  - dysk
  - everforest
  - flyline
  - georglauterbach
  - gitui
  - gsettings
  - perfmon
  - reqwest
  - rustdoc
  - rustls
  - setcap
  - sharkdp
  - sigusr2
  - softprops
  - trixie
  - xattrs
  - yazi
  - zizmor
  - zstd
