#! /usr/bin/env bash

# ██████╗  █████╗ ███████╗██╗  ██╗
# ██╔══██╗██╔══██╗██╔════╝██║  ██║
# ██████╔╝███████║███████╗███████║
# ██╔══██╗██╔══██║╚════██║██╔══██║
# ██████╔╝██║  ██║███████║██║  ██║          task  user-wide shell (Bash) initialization
# ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝    sourced by  (usually) interactive non-login shells

# ! Do not edit this file - use ${HOME}/.config/bash/{20-custom_early,99-custom_late}.sh instead.

# -----------------------------------------------
# ----  Basic Setup  ----------------------------
# -----------------------------------------------

function __is_command() {
  command -v "${1:?Command name required in __is_command}" &>/dev/null
}

function __evaluates_to_true() {
  local -n INPUT=${1:?Input for evaluation required in __evaluates_to_true}
  [[ -v ${1} ]] && [[ ${INPUT,,} == 'true' ]]
}

export -f __is_command __evaluates_to_true

# -----------------------------------------------
# ----  Interactive Setup  ----------------------
# -----------------------------------------------

if [[ ${-} == *i* ]]; then
  function __bash_setup() {
    local SETUP_FILE_PREFIX="${HOME}/.config/bash"
    function __load_script() {
      local SCRIPT_FILE=${1:?Path to script to load is required}
      # shellcheck source=/dev/null
      [[ -e ${SCRIPT_FILE} ]] && [[ -r ${SCRIPT_FILE} ]] && source "${SCRIPT_FILE}"
    }

    __load_script "${HERMES_CUSTOM_EARLY_SCRIPT:-${SETUP_FILE_PREFIX}/20-custom_early.sh}"
    __load_script "${SETUP_FILE_PREFIX}/50-hermes.sh"
    __load_script "${HERMES_CUSTOM_LATE_SCRIPT:-${SETUP_FILE_PREFIX}/99-custom_late.sh}"

    [[ -v BLE_VERSION ]] && ble-attach
  }

  __bash_setup || :
  unset __bash_setup __load_script
fi
