#! /usr/bin/env bash

# ! DO NOT EDIT THIS FILE
# ! USE ${HOME}/.config/bash/91-hermes_settings.sh INSTEAD

[[ ${-} == *i* ]] || return 0

function __is_command() {
  command -v "${1:?Command name required in __is_command}" &>/dev/null
}

function __evaluates_to_true() {
  local -n INPUT=${1:?Input for evaluation required in __evaluates_to_true}
  [[ -v ${1} ]] && [[ ${INPUT,,} == 'true' ]]
}

# shellcheck disable=SC2066
function __hermes__setup_path() {
  local PATH_SEGMENT
  export PATH=${PATH:-'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'}

  for PATH_SEGMENT in "${HOME}/.local/bin"; do
    if [[ -d ${PATH_SEGMENT} ]] && [[ -r ${PATH_SEGMENT} ]] && [[ ${PATH} != *${PATH_SEGMENT}* ]]; then
      PATH="${PATH_SEGMENT}:${PATH}"
    fi
  done

  for PATH_SEGMENT in "${HOME}/.cargo/env"; do
    # shellcheck source=/dev/null
    [[ -s ${PATH_SEGMENT} ]] && [[ -r ${PATH_SEGMENT} ]] && source "${PATH_SEGMENT}"
  done
}

function __hermes__setup_variables() {
  # common editor
  if [[ ! -v VISUAL ]]; then
    if   __is_command 'nvim' ; then VISUAL='nvim'
    elif __is_command 'vim'  ; then VISUAL='vim'
    elif __is_command 'vi'   ; then VISUAL='vi'
    elif __is_command 'nano' ; then VISUAL='nano'
    else VISUAL=
    fi
  fi

  command -v less &>/dev/null && PAGER=${PAGER:-$(command -v less)}
  EDITOR=${EDITOR:-${VISUAL}}
  GPG_TTY=$(tty)

  export VISUAL EDITOR PAGER GPG_TTY

  if [[ ! -v LANG ]]; then
    # shellcheck source=/dev/null
    [[ -e /etc/locale.conf ]] && source /etc/locale.conf
    export LANG=${LANG:-C.UTF-8}
    export LANGUAGE=${LANGUAGE:-${LANG}}
    export LC_ALL=${LC_ALL:-${LANG}}
  fi
}

function __hermes__setup_completion() {
  shopt -oq posix && return 0

  if [[ -r ${XDG_CONFIG_HOME:-${HOME}/.config}/bash_completion ]]; then
    # shellcheck source=/dev/null
    source "${XDG_CONFIG_HOME:-${HOME}/.config}/bash_completion"
  fi

  if [[ -r /usr/share/bash-completion/bash_completion ]]; then
    # shellcheck source=/dev/null
    source /usr/share/bash-completion/bash_completion
  fi
}

function __hermes__setup_history() {
  # cSpell: ignore ignoreboth histappend

  export HISTFILE=${HISTFILE:-${HOME}/.cache/bash/history.txt}
  export HISTCONTROL=${HISTCONTROL:-ignoreboth}
  export HISTSIZE=${HISTSIZE:-10000}
  export HISTFILESIZE=${HISTFILESIZE:-10000}

  shopt -s histappend
}

function __hermes__setup_prompt() {
  # cSpell: ignore dirtrim libflyline dircolors

  if __evaluates_to_true HERMES_INIT_STARSHIP && __is_command 'starship'; then
    [[ -v STARSHIP_CONFIG ]] || STARSHIP_CONFIG="${HOME}/.config/starship/starship.toml"
    export STARSHIP_CONFIG
    eval "$(starship init bash || :)"
    # We disable PS0 and preexec hooks because
    # they mess with trapping signals like SIGUSR2
    unset -f starship_preexec_ps0 2>/dev/null
    PS0=''
    if __evaluates_to_true HERMES_INIT_FLYLINE; then
      # shellcheck disable=SC2016
      export PS1_FINAL='$(starship module directory) ➜ ' RPS1_FINAL='' PS1_FILL_FINAL=''
    fi
  else
    export PROMPT_DIRTRIM=4
    export PS2=''   # continuation shell prompt
    export PS4='> ' # `set -x` tracing prompt

    # shellcheck disable=SC2155
    if [[ ! -v debian_chroot ]] && [[ -r /etc/debian_chroot ]]; then
      export debian_chroot=$(</etc/debian_chroot)
    fi
  fi

  if __evaluates_to_true HERMES_INIT_FLYLINE && [[ -s "${HOME}/.local/lib/libflyline.so" ]]; then
    eval "$(dircolors || :)" # LS_COLORS for coloring completions
    __is_command flyline || enable -f "${HOME}/.local/lib/libflyline.so" flyline

    flyline editor      --auto-close-chars false
    flyline editor      --show-inline-history true
    flyline mouse       --mode disabled
    flyline suggestions set-fuzzy-mode none

    if [[ ! -v __HERMES__FLYLINE_BASE_COLORS ]]; then
      readonly __HERMES__FLYLINE_BASE_COLORS=(
        recognised-command='green'
        unrecognised-command='bold red'
        single-quoted-text='yellow'
        double-quoted-text='yellow'
        inline-suggestion='cyan'
        key-sequence-style='red'
        opening-and-closing-pair='magenta'
        rainbow-bracket1='blue'
        rainbow-bracket2='dim blue'
        rainbow-bracket3='purple'
        rainbow-bracket4='dim purple'
      )
    fi
  fi
}

function __hermes__setup_extra_programs() {
  # cSpell: ignore gsub manroffopt

  if __evaluates_to_true HERMES_INIT_BAT && __is_command 'bat'; then
    export BAT_STYLE='plain'
    export BAT_THEME_DARK='evergruv-dark'
    export BAT_THEME_LIGHT='evergruv-light'

    if [[ -v PAGER ]]; then
      export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat --plain --language=man'"
      export MANROFFOPT='-c'
    fi
  fi

  if __evaluates_to_true HERMES_INIT_FZF && __is_command 'fzf'; then
    # shellcheck source=/dev/null
    source <(fzf --bash)
  fi

  if __evaluates_to_true HERMES_INIT_ZOXIDE && __is_command 'zoxide'; then
    # shellcheck source=/dev/null
    source <(zoxide init bash)
  fi
}

function __hermes__setup_overrides() {
  # The checks on `[[ -t 0 ]]` guard against missing stdin, which
  # is a problem in agent sessions because it leads to hanging.

  if __evaluates_to_true HERMES_OVERRIDE_CAT_WITH_BAT && __is_command 'bat'; then
    # shellcheck disable=SC2329
    function cat() {
      if [[ -t 0 ]]
      then command bat --paging=never "${@}"
      else command cat "${@}"
      fi
    }
    export -f cat
  fi

  if __evaluates_to_true HERMES_OVERRIDE_CD_WITH_ZOXIDE && __is_command 'zoxide'; then
    alias cd='z'
  fi

  if __evaluates_to_true HERMES_OVERRIDE_DIFF_WITH_DELTA && __is_command 'delta'; then
    # shellcheck disable=SC2329
    function diff() {
      if [[ -t 0 ]]
      then command delta --line-numbers "${@}"
      else command diff "${@}"
      fi
    }
    export -f diff
  fi

  if __evaluates_to_true HERMES_OVERRIDE_LESS_WITH_BAT && __is_command 'bat'; then
    # shellcheck disable=SC2329
    function less() {
      if [[ -t 0 ]]
      then command bat --paging=always "${@}"
      else command less "${@}"
      fi
    }
    export -f less
  fi

  if __evaluates_to_true HERMES_OVERRIDE_LS_WITH_EZA && __is_command 'eza'; then
    # shellcheck disable=SC2329
    function ls() {
      if [[ -t 0 ]]
      then command eza --header --long --binary --group --classify --extended --group-directories-first "${@}"
      else command ls "${@}"
      fi
    }
    export -f ls
  fi

  if __evaluates_to_true HERMES_OVERRIDE_Y_WITH_YAZI && __is_command 'yazi'; then
    # shellcheck disable=SC2329
    function y() {
      local YAZI_TMP_FILE YAZI_CWD
      YAZI_TMP_FILE="$(mktemp -t "yazi-cwd.XXXXXX")"
      yazi "${@}" --cwd-file="${YAZI_TMP_FILE}"
      IFS= read -r -d '' YAZI_CWD < "${YAZI_TMP_FILE}"
      [[ -n ${YAZI_CWD:-} ]] && [[ ${YAZI_CWD} != "${PWD}" ]] && { builtin cd -- "${YAZI_CWD}" || return 1 ; }
      rm --force -- "${YAZI_TMP_FILE}"
    }
    export -f y
  fi
}

function __hermes__setup_aliases() {
  if __evaluates_to_true HERMES_LOAD_GLOBAL_ALIASES; then
    alias gcs='git commit --signoff --gpg-sign'
    alias gp='git pull'
    alias gf='git fetch --prune --tags --force'

    alias lsa='ls -A'

    if [[ -n ${EDITOR} ]]; then
      # shellcheck disable=SC2139
      alias v="${EDITOR:-vi}"
      # shellcheck disable=SC2139
      alias sv="sudo $(command -v "${EDITOR:-vi}")"
    fi

    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias .....='cd ../../../..'
    alias ......='cd ../../../../..'
    alias .......='cd ../../../../../..'
  fi
}

if [[ -s ${HOME}/.config/bash/91-hermes_settings.sh ]]; then
  # shellcheck disable=SC1091
  # shellcheck source=91-hermes_settings.sh
  source "${HOME}/.config/bash/91-hermes_settings.sh"
fi

# cSpell: ignore checkwinsize autocd
shopt -s checkwinsize globstar autocd

for __FUNCTION in path variables completion history prompt extra_programs overrides aliases; do
  "__hermes__setup_${__FUNCTION}" || :
  unset "__hermes__setup_${__FUNCTION}"
done

function __hermes__signal_handler_sigusr2() {
  if __evaluates_to_true HERMES_INIT_FLYLINE; then
    if [[ $(gsettings get org.gnome.desktop.interface color-scheme) == "'prefer-light'" ]]; then
      flyline set-style "${__HERMES__FLYLINE_BASE_COLORS[@]}" \
        normal-text='dim black' secondary-text='black'
    else
      flyline set-style "${__HERMES__FLYLINE_BASE_COLORS[@]}" \
        normal-text='white' secondary-text='dim white'
    fi
  fi
}

trap __hermes__signal_handler_sigusr2 SIGUSR2
__hermes__signal_handler_sigusr2
