# syntax=docker.rsint.net/docker.io/docker/dockerfile:1

# This base image's purpose is to be used as an image that you
# inherit from for a Development Container. It already contains
# useful packages and does not require additional setup. It
# "just works".
#
# ref: https://github.com/georglauterbach/dev-container-base
FROM docker.rsint.net/ghcr.io/georglauterbach/dev-container-base:3.0.1

SHELL [ "/bin/bash", "-eE", "-u", "-o", "pipefail", "-c" ]
