#! /usr/bin/env bash

# ! DO NOT EDIT THIS FILE
# ! USE ${HOME}/.config/bash/91-hermes_settings.sh INSTEAD

[[ ${-} == *i* ]] || return 0

function __is_command() {
  command -v "${1:?Command name required in __is_command}" &>/dev/null
}

function __evaluates_to_true() {
  local -n INPUT=${1:?Input for evaluation required in __evaluates_to_true}
  [[ -v ${1} ]] && [[ ${INPUT,,} == 'true' ]]
}

function __hermes__setup_variables() {
  local PATH_SEGMENT
  export PATH=${PATH:-'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'}

  # shellcheck disable=SC2066
  for PATH_SEGMENT in "${HOME}/.local/bin"; do
    if [[ -d ${PATH_SEGMENT} ]] && [[ -r ${PATH_SEGMENT} ]] && [[ ${PATH} != *${PATH_SEGMENT}* ]]; then
      PATH="${PATH_SEGMENT}:${PATH}"
    fi
  done

  # shellcheck disable=SC2066
  for PATH_SEGMENT in "${HOME}/.cargo/env"; do
    # shellcheck source=/dev/null
    [[ -s ${PATH_SEGMENT} ]] && [[ -r ${PATH_SEGMENT} ]] && source "${PATH_SEGMENT}"
  done

  if [[ ! -v VISUAL ]]; then
    if   __is_command 'nvim' ; then VISUAL='nvim'
    elif __is_command 'vim'  ; then VISUAL='vim'
    elif __is_command 'vi'   ; then VISUAL='vi'
    elif __is_command 'nano' ; then VISUAL='nano'
    else VISUAL=''
    fi
  fi

  EDITOR=${EDITOR:-${VISUAL}}
  GPG_TTY=$(tty)
  command -v less &>/dev/null && PAGER=${PAGER:-$(command -v less)}

  export VISUAL EDITOR PAGER GPG_TTY

  if [[ ! -v LANG ]]; then
    # shellcheck source=/dev/null
    [[ -e /etc/locale.conf ]] && source /etc/locale.conf
    export LANG=${LANG:-C.UTF-8}
    export LANGUAGE=${LANGUAGE:-${LANG}}
    export LC_ALL=${LC_ALL:-${LANG}}
  fi
}

function __hermes__setup_completion() {
  shopt -oq posix && return 0

  if [[ -r ${XDG_CONFIG_HOME:-${HOME}/.config}/bash_completion ]]; then
    # shellcheck source=/dev/null
    source "${XDG_CONFIG_HOME:-${HOME}/.config}/bash_completion"
  fi

  if [[ -r /usr/share/bash-completion/bash_completion ]]; then
    # shellcheck source=/dev/null
    source /usr/share/bash-completion/bash_completion
  fi
}

function __hermes__setup_history() {
  # cSpell: ignore ignoreboth histappend

  export HISTFILE=${HISTFILE:-${HOME}/.cache/bash/history.txt}
  export HISTCONTROL=${HISTCONTROL:-ignoreboth}
  export HISTSIZE=${HISTSIZE:-10000}
  export HISTFILESIZE=${HISTFILESIZE:-10000}

  shopt -s histappend
}

function __hermes__setup_prompt() {
  # cSpell: ignore dirtrim libflyline dircolors

  if __evaluates_to_true HERMES_INIT_STARSHIP && __is_command 'starship'; then
    [[ -v STARSHIP_CONFIG ]] || STARSHIP_CONFIG="${HOME}/.config/starship/starship.toml"
    export STARSHIP_CONFIG
    eval "$(starship init bash || :)"
    # We disable PS0 and preexec hooks because
    # they mess with trapping signals like SIGUSR2
    unset -f starship_preexec_ps0 2>/dev/null
    PS0=''
    if __evaluates_to_true HERMES_INIT_FLYLINE; then
      # shellcheck disable=SC2016
      export PS1_FINAL='$(starship module directory) ➜ ' RPS1_FINAL='' PS1_FILL_FINAL=''
    fi
  else
    export PROMPT_DIRTRIM=4
    export PS2=''   # continuation shell prompt
    export PS4='> ' # `set -x` tracing prompt

    # shellcheck disable=SC2155
    if [[ ! -v debian_chroot ]] && [[ -r /etc/debian_chroot ]]; then
      export debian_chroot=$(</etc/debian_chroot)
    fi
  fi

  if __evaluates_to_true HERMES_INIT_FLYLINE && [[ -s "${HOME}/.local/lib/libflyline.so" ]]; then
    eval "$(dircolors || :)" # LS_COLORS for coloring completions
    __is_command flyline || enable -f "${HOME}/.local/lib/libflyline.so" flyline

    flyline editor      --auto-close-chars false
    flyline editor      --show-inline-history true
    flyline mouse       --mode disabled
    flyline suggestions set-fuzzy-mode none

    if [[ ! -v __HERMES__FLYLINE_BASE_COLORS ]]; then
      readonly __HERMES__FLYLINE_BASE_COLORS=(
        recognised-command='green'
        unrecognised-command='bold red'
        single-quoted-text='yellow'
        double-quoted-text='yellow'
        inline-suggestion='cyan'
        key-sequence-style='red'
        opening-and-closing-pair='magenta'
        rainbow-bracket1='blue'
        rainbow-bracket2='dim blue'
        rainbow-bracket3='purple'
        rainbow-bracket4='dim purple'
      )
    fi

    # shellcheck disable=SC2329
    function __hermes__set_flyline_theme() {
      local THEME_VARIANT=${1:?theme variant required __hermes__set_flyline_theme}

      # cSpell: disable-next-line
      if [[ ${THEME_VARIANT} =~ ^l(ight)?$ ]]; then
        flyline set-style "${__HERMES__FLYLINE_BASE_COLORS[@]}" \
          normal-text='dim black' secondary-text='black'
      elif [[ ${THEME_VARIANT} =~ ^d(ark)?$ ]]; then
        flyline set-style "${__HERMES__FLYLINE_BASE_COLORS[@]}" \
          normal-text='white' secondary-text='dim white'
      else
        echo "WARN  Theme variant '${THEME_VARIANT}' unknown - use 'light' or 'dark'" >&2
        return 1
      fi
    }
    export -f __hermes__set_flyline_theme
  fi
}

function __hermes__setup_programs() {
  # cSpell: ignore gsub manroffopt

  if __evaluates_to_true HERMES_INIT_BAT && __is_command 'bat'; then
    export BAT_STYLE='plain'
    export BAT_THEME_DARK='evergruv-dark'
    export BAT_THEME_LIGHT='evergruv-light'

    if [[ -v PAGER ]]; then
      export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat --plain --language=man'"
      export MANROFFOPT='-c'
    fi
  fi

  if __evaluates_to_true HERMES_INIT_FZF && __is_command 'fzf'; then
    # shellcheck source=/dev/null
    source <(fzf --bash)

    export FZF_DEFAULT_OPTS_BASE=${FZF_DEFAULT_OPTS}

    # shellcheck disable=SC2329
    function __hermes__set_fzf_theme() {
      local THEME_VARIANT=${1:?theme variant required __hermes__set_flyline_theme}

      # cSpell: disable-next-line
      if [[ ${THEME_VARIANT} =~ ^l(ight)?$ ]]; then
        export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS_BASE} --color=light --color=fg:#5C6A72,bg:#F5F5F2,hl:#8DA101 --color=fg+:#5C6A72,bg+:#EBEBE4,hl+:#8DA101 --color=info:#D69A00,prompt:#8DA101,pointer:#3A94C5 --color=marker:#8DA101,spinner:#35A77C,header:#8DA101 --color=border:#EBEBE4,gutter:#F5F5F2,query:#5C6A72 --color=scrollbar:#8DA101,separator:#EBEBE4"
      elif [[ ${THEME_VARIANT} =~ ^d(ark)?$ ]]; then
        export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS_BASE} --color=dark --color=fg:#DDC7A1,bg:#1D2021,hl:#A9B665 --color=fg+:#DDC7A1,bg+:#141617,hl+:#A9B665 --color=info:#D8A657,prompt:#A9B665,pointer:#7DAEA3 --color=marker:#A9B665,spinner:#89B482,header:#A9B665 --color=border:#141617,gutter:#1D2021,query:#DDC7A1 --color=scrollbar:#A9B665,separator:#141617"
      else
        echo "WARN  Theme variant '${THEME_VARIANT}' unknown - use 'light' or 'dark'" >&2
        return 1
      fi
    }
    export -f __hermes__set_fzf_theme
  fi

  if __evaluates_to_true HERMES_INIT_ZELLIJ && __is_command 'zellij'; then
    alias zj='zellij'
    alias zd='zellij action detach'

    # shellcheck disable=SC2329
    function zat() {
      if [[ -n ${ZELLIJ:-} ]]; then
        echo 'Running Zellij in Zellij is not supported' >&2
        return 1
      fi

      if git status &>/dev/null; then
        zellij attach --create "$(basename "${PWD}")"
        return "${?}"
      fi

      local SESSIONS SELECTED_SESSION

      SESSIONS=$(zellij ls 2>/dev/null)
      if [[ -z ${SESSIONS} ]]; then
        echo 'There are no Zellij sessions available'
        return 0
      fi

      if ! __is_command fzf; then
        echo "Command 'fzf' required but not found" >&2
        return 1
      fi

      SELECTED_SESSION="$(fzf --ansi <<< "${SESSIONS}" |& awk '{print $1}')"
      [[ -n ${SELECTED_SESSION} ]] || return 0

      zellij attach --create "${SELECTED_SESSION}"
    }
    export -f zat
  fi

  if __evaluates_to_true HERMES_INIT_ZOXIDE && __is_command 'zoxide'; then
    # shellcheck source=/dev/null
    source <(zoxide init bash)
  fi
}

function __hermes__setup_overrides() {
  # The checks on `[[ -t 0 ]]` guard against missing stdin, which
  # is a problem in agent sessions because it leads to hanging.

  if __evaluates_to_true HERMES_OVERRIDE_CAT_WITH_BAT && __is_command 'bat'; then
    # shellcheck disable=SC2329
    function cat() {
      if [[ -t 0 ]]
      then command bat --paging=never "${@}"
      else command cat "${@}"
      fi
    }
    export -f cat
  fi

  if __evaluates_to_true HERMES_OVERRIDE_CD_WITH_ZOXIDE && __is_command 'zoxide'; then
    alias cd='z'
  fi

  if __evaluates_to_true HERMES_OVERRIDE_DIFF_WITH_DELTA && __is_command 'delta'; then
    # shellcheck disable=SC2329
    function diff() {
      if [[ -t 0 ]]
      then command delta --line-numbers "${@}"
      else command diff "${@}"
      fi
    }
    export -f diff
  fi

  if __evaluates_to_true HERMES_OVERRIDE_LESS_WITH_BAT && __is_command 'bat'; then
    # shellcheck disable=SC2329
    function less() {
      if [[ -t 0 ]]
      then command bat --paging=always "${@}"
      else command less "${@}"
      fi
    }
    export -f less
  fi

  if __evaluates_to_true HERMES_OVERRIDE_LS_WITH_EZA && __is_command 'eza'; then
    # shellcheck disable=SC2329
    function ls() {
      if [[ -t 0 ]]
      then command eza --header --long --binary --group --classify --extended --group-directories-first "${@}"
      else command ls "${@}"
      fi
    }
    export -f ls
  fi

  if __evaluates_to_true HERMES_OVERRIDE_Y_WITH_YAZI && __is_command 'yazi'; then
    # shellcheck disable=SC2329
    function y() {
      local YAZI_TMP_FILE YAZI_CWD
      YAZI_TMP_FILE="$(mktemp -t "yazi-cwd.XXXXXX")"
      yazi "${@}" --cwd-file="${YAZI_TMP_FILE}"
      IFS= read -r -d '' YAZI_CWD < "${YAZI_TMP_FILE}"
      [[ -n ${YAZI_CWD:-} ]] && [[ ${YAZI_CWD} != "${PWD}" ]] && { builtin cd -- "${YAZI_CWD}" || return 1 ; }
      rm --force -- "${YAZI_TMP_FILE}"
    }
    export -f y
  fi
}

function __hermes__setup_aliases() {
  if __evaluates_to_true HERMES_LOAD_GLOBAL_ALIASES; then
    alias gcs='git commit --signoff --gpg-sign'
    alias gp='git pull'
    alias gf='git fetch --prune --tags --force'

    alias lsa='ls -A'

    if [[ -n ${EDITOR} ]]; then
      # shellcheck disable=SC2139
      alias v="${EDITOR:-vi}"
      # shellcheck disable=SC2139
      alias sv="sudo $(command -v "${EDITOR:-vi}")"
    fi

    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias .....='cd ../../../..'
    alias ......='cd ../../../../..'
    alias .......='cd ../../../../../..'
  fi
}

function __hermes__setup_signal_handlers() {
  # When hermes is used in conjunction with https://github.com/georglauterbach/desktop,
  # theme variant changes to certain CLI utilities (that cannot be updated in another way)
  # can be applied with the `theme` script; for this to work properly, we need to handle
  # the 'SIGUSR2' signal.
  function __hermes__signal_handler_sigusr2() {
    local THEME_VARIANT
    THEME_VARIANT=$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null || :)

    if   [[ ${THEME_VARIANT} == "'prefer-light'" ]]; then THEME_VARIANT=light
    elif [[ ${THEME_VARIANT} == "'prefer-dark'" ]];  then THEME_VARIANT=dark
    else return 0
    fi

    __evaluates_to_true HERMES_INIT_FLYLINE && __hermes__set_flyline_theme "${THEME_VARIANT}" || :
    __evaluates_to_true HERMES_INIT_FZF && __hermes__set_fzf_theme "${THEME_VARIANT}" || :
    return 0
  }

  # To perform cleanup of the current shell's PID, we run a dedicated script when we
  # receive the 'EXIT' signal. Not doing this is not an issue because the `theme` script
  # (https://github.com/georglauterbach/desktop) will also clean up - having this handler
  # is simply an optimization.
  # shellcheck disable=SC2329
  function __hermes__signal_handler_exit() {
    # We ignore SC2094 because we fully read the file first and overwrite it only afterward.
    # shellcheck disable=SC2094
    {
      flock -x 3
      grep -v ${$} <&3 >/tmp/.hermes_shells_to_update_exit || :
      mv /tmp/.hermes_shells_to_update_exit /tmp/.hermes_shells_to_update
    } 3</tmp/.hermes_shells_to_update
  }

  export -f __hermes__signal_handler_sigusr2 __hermes__signal_handler_exit

  trap __hermes__signal_handler_sigusr2 SIGUSR2
  trap __hermes__signal_handler_exit EXIT

  { flock -x 3 ; echo "${$}" >&3 ; } 3>>/tmp/.hermes_shells_to_update
  __hermes__signal_handler_sigusr2
}

if [[ -s ${HOME}/.config/bash/91-hermes_settings.sh ]]; then
  # shellcheck disable=SC1091
  # shellcheck source=91-hermes_settings.sh
  source "${HOME}/.config/bash/91-hermes_settings.sh"
fi

# cSpell: ignore checkwinsize autocd
shopt -s checkwinsize globstar autocd

for __FUNCTION in variables completion history prompt programs overrides aliases signal_handlers; do
  "__hermes__setup_${__FUNCTION}" || :
  unset "__hermes__setup_${__FUNCTION}"
done

function download_hermes_latest() {
  local HERMES_LOCATION="${HOME}/.local/bin/hermes"
  local HERMES_RELEASE_URI_BASE='https://github.com/georglauterbach/hermes/releases'
  local HERMES_VERSION

  HERMES_VERSION=$(curl --silent --show-error --fail --location --write-out '%{url_effective}' --output /dev/null \
    "${HERMES_RELEASE_URI_BASE}/latest" | sed 's|.*/||')

  mkdir --parents "$(dirname "${HERMES_LOCATION}")"
  curl --silent --show-error --fail --location --output "${HERMES_LOCATION}" \
    "${HERMES_RELEASE_URI_BASE}/download/${HERMES_VERSION}/hermes-${HERMES_VERSION}-$(uname -m)-unknown-linux-musl"

  chmod +x "${HERMES_LOCATION}"
}
