[colors.cursor]
cursor = "#7DA101"
text = "#FFFBEF"

[colors.primary]
background = "#FFFBEF"
foreground = "#5C6A72"

[colors.normal]
black = "#5C6A72"
white = "#FFFBEF"

red = "#F85552"
yellow = "#DFA000"
green = "#8DA101"
cyan = "#35A77C"
blue = "#3A94C5"
magenta = "#DF69BA"
