[colors.primary]
background = "#FAFAFA"
foreground = "#4B505B"

[colors.normal]
black = "#000000"
white = "#FFFFFF"

red = "#D05858"
yellow = "#BE7E05"
green = "#608E32"
cyan = "#3A8B84"
blue = "#5079BE"
magenta = "#B05CCC"

[window]
opacity = 1
