#! /usr/bin/env bash

# sourced by  ${HOME}/.bashrc or manually
#       task  usable even when not running interactively to
#             provide basic functionality and initialization

# ! Do not edit this file - use ${HOME}/.config/bash/{20-custom_early,99-custom_late}.sh instead.

function __is_command() {
  command -v "${1:?Command name is required}" &>/dev/null
}

function __evaluates_to_true() {
  local -n INPUT=${1:?Input for evaluation required}
  [[ -v ${1} ]] || return 1
  [[ ${INPUT,,} == 'true' ]]
}

function __hermes__setup_path() {
  local LOOP_VAR_PATH
  export PATH=${PATH:-/bin}

  for LOOP_VAR_PATH in "${HOME}/bin" "${HOME}/.local/bin"; do
    if [[ -d ${LOOP_VAR_PATH} ]] && [[ ${PATH} != *${LOOP_VAR_PATH}* ]]; then
      PATH="${LOOP_VAR_PATH}:${PATH}"
    fi
  done

  # shellcheck disable=SC2066
  for LOOP_VAR_PATH in "${HOME}/.cargo/env"; do
    if [[ -e ${LOOP_VAR_PATH} ]] && [[ -r ${LOOP_VAR_PATH} ]]; then
      # shellcheck source=/dev/null
      source "${LOOP_VAR_PATH}"
    fi
  done
}

__hermes__setup_path
unset __hermes__setup_path
