#! /usr/bin/env bash

#    version  2.0.0
# sourced by  ${HOME}/.bashrc
#       task  miscellaneous setup

# ! Do not edit this file - use ${HOME}/.config/bash/{20-custom_early,99-custom_late}.sh instead.

function __hermes__setup_misc() {
  # shell options
  shopt -s checkwinsize globstar autocd

  # miscellaneous environment variables
  VISUAL='nano'
  if   __is_command 'nvim'; then VISUAL='nvim'
  elif __is_command 'vim' ; then VISUAL='vim'
  elif __is_command 'vi'  ; then VISUAL='vi'
  fi

  EDITOR=${VISUAL}
  PAGER="$(command -v less) -R"
  GPG_TTY=$(tty)
  HERMES_LOADED=true

  export VISUAL EDITOR PAGER GPG_TTY HERMES_LOADED

  # completion
  if ! shopt -oq posix; then
    if [[ -f /etc/profile.d/bash_completion.sh ]]; then
      # shellcheck source=/dev/null
      source /etc/profile.d/bash_completion.sh
    elif [[ -f /etc/bash_completion ]]; then
      # shellcheck source=/dev/null
      source /etc/bash_completion
    fi
  fi
}

function __hermes__setup_prompt() {
  if ! __evaluates_to_true HERMES_INIT_STARSHIP || ! __is_command 'starship'; then
    export PROMPT_DIRTRIM=4
    export PS2=''   # continuation shell prompt
    export PS4='> ' # `set -x` tracing prompt

    # shellcheck disable=SC2155
    [[ -v debian_chroot ]] && [[ -r /etc/debian_chroot ]] && export debian_chroot=$(</etc/debian_chroot)
    return 0
  fi

  export STARSHIP_CONFIG=${STARSHIP_CONFIG:-${HOME}/.config/starship/starship.toml}
  if [[ ! -f ${STARSHIP_CONFIG} ]] || [[ ! -r ${STARSHIP_CONFIG} ]]; then
    echo "hermes: Starship configuration file '${STARSHIP_CONFIG}' does exist or is not readable" >&2
    unset STARSHIP_CONFIG
  fi

  eval "$(starship init bash || :)"
}

__hermes__setup_misc
__hermes__setup_prompt
unset __hermes__setup_misc __hermes__setup_prompt
