#! /usr/bin/env bash

# version       0.1.1
# sourced by    ${HOME}/.bashrc
# task          overwrite well-known commands with modern alternatives

# shellcheck disable=SC2317

# ! Do not edit this file.
# ! Use ${HOME}/.config/bash/{20-custom_early,99-custom_late}.sh instead.

# Overrides the `apt` command by executing `nala` if
# `nala` is in `${PATH}`; otherwise, execute `apt`.
function __hermes__override_apt_with_nala() {
  __evaluates_to_true HERMES_OVERRIDE_APT_WITH_NALA 'false' || return 0

  function apt() {
    local PROGRAM='apt'
    __is_command 'nala' && PROGRAM='nala'

    if [[ ${1:-} =~ ^show|search$ ]]
    then
      command "${PROGRAM}" "${@}"
    else
      __do_as_root "${PROGRAM}" "${@}"
    fi
  }; export -f apt
}

# Overrides the `cat` command by executing `bat` if
# `bat` is in `${PATH}`; otherwise, execute `cat`.
function __hermes__override_cat_with_bat() {
  __evaluates_to_true HERMES_OVERRIDE_CAT_WITH_BAT 'false' || return 0

  if __is_command 'bat'; then
    alias cd='bat'
  elif __is_command 'batcat'; then
    alias cd='batcat'
  fi
}

# Overrides the `apt` command by executing `nala` if
# `nala` is in `${PATH}`; otherwise, execute `apt`.
function __hermes__override_cd_with_zoxide() {
  __evaluates_to_true HERMES_OVERRIDE_CD_WITH_ZOXIDE 'false' || return 0
  __is_command 'zoxide' && alias cd='z'
}

# Overrides the `find` command by executing `fd` if
# `fd` is in `${PATH}`; otherwise, execute `find`.
# This will only happen in interactive mode.
function __hermes__override_find_with_fd() {
  __evaluates_to_true HERMES_OVERRIDE_FIND_WITH_FD 'false' || return 0
  [[ ${-} == *i* ]] || return 0
  __is_command 'fd' && alias find='fd'
}

# Overrides the `grep` command by executing `ripgrep` if
# `ripgrep` is in `${PATH}`; otherwise, execute `grep`.
# This will only happen in interactive mode.
function __hermes__override_grep_with_ripgrep() {
  __evaluates_to_true HERMES_OVERRIDE_GREP_WITH_RIPGREP 'false' || return 0
  [[ ${-} == *i* ]] || return 0
  __is_command 'rg' && alias grep='rg'
}

# Overrides the `ls` command by executing `eza` if
# `eza` is in `${PATH}`; otherwise, execute `ls`.
function __hermes__override_ls_with_eza() {
  __evaluates_to_true HERMES_OVERRIDE_LS_WITH_EZA 'false' || return 0
  __is_command 'eza' && alias ls='eza --header --long --binary --group --classify --extended --group-directories-first'
}

for __FUNCTION in 'apt_with_nala' 'cat_with_bat' 'cd_with_zoxide' \
                  'find_with_fd' 'grep_with_ripgrep' 'ls_with_eza'; do
  "__hermes__override_${__FUNCTION}" || :
  unset "__hermes__override_${__FUNCTION}"
done
