VERSION 0.6

FROM docker.io/alpine:3.23

RUN apk add --no-cache build-base cmake coreutils curl gettext-tiny-dev git

ARG NEOVIM_VERSION=0.11.5

build-all-platforms:
    BUILD --platform=linux/amd64 +build # --platform=linux/arm64

build:
    ARG TARGETARCH

    RUN curl -sSfL -o "neovim_v${NEOVIM_VERSION}.tar.gz" \
      "https://github.com/neovim/neovim/archive/refs/tags/v${NEOVIM_VERSION}.tar.gz"
    RUN tar xf "neovim_v${NEOVIM_VERSION}.tar.gz"
    WORKDIR "/neovim-${NEOVIM_VERSION}"

    RUN make -j"$(nproc)" CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DSTATIC_BUILD=1"
    SAVE ARTIFACT build/bin/nvim AS LOCAL ./out/${TARGETARCH}/
