---
name: Build and Test
run-name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build_x86_64:
    name: x86_64
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Test
        uses: devcontainers/ci@v0.3
        with:
          push: never
          configFile: .devcontainer/development/devcontainer.json
          runCmd: |
            cd code
            cargo fmt    --quiet -- --check
            cargo build  --quiet --release --target x86_64-unknown-linux-musl
            cargo clippy --quiet --release --target x86_64-unknown-linux-musl --all-features -- -D warnings
            cargo doc    --quiet --release --target x86_64-unknown-linux-musl --document-private-items
            cargo test   --quiet --release --target x86_64-unknown-linux-musl

            cp \
              code/target/x86_64-unknown-linux-musl/release/hermes
              code/target/hermes-${{ github.ref_name }}-x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: code/target/hermes-${{ github.ref_name }}-x86_64-unknown-linux-musl

  build_aarch64:
    name: aarch64
    runs-on: ubuntu-24.04
    needs: build_x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          configFile: .devcontainer/development/devcontainer.json
          runCmd: |
            export CC=aarch64-linux-gnu-gcc
            cd code
            cargo build  --quiet --release --target aarch64-unknown-linux-musl
            cp \
              code/target/aarch64-unknown-linux-musl/release/hermes
              code/target/hermes-${{ github.ref_name }}-aarch64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: code/target/hermes-${{ github.ref_name }}-aarch64-unknown-linux-musl
