---
name: Integration
run-name: Integration

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ code/**, .github/** ]
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ '**' ]
    paths: [ code/**, .github/** ]

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: docker.io/rust:1.90.0-slim-trixie

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Packages
        run: |
          apt-get --yes --quiet=2 update
          apt-get --yes install binutils-aarch64-linux-gnu gcc gcc-aarch64-linux-gnu musl-tools pkg-config zstd

      - name: Test & Lint Code
        run: |
          mkdir --parents .assets/x86_64
          touch           .assets/x86_64/archive.tar.xz

          cd code

          cargo fmt    --all                              -- --check
          cargo clippy --workspace --quiet --all-features -- -D warnings
          cargo doc    --workspace --quiet --no-deps --document-private-items

      - name: Build
        run: |
          cd code

          cargo run --package cupid -- --architecture x86-64
          cargo run --package cupid -- --architecture aarch64

          export CARGO_BUILD_TARGET=x86_64-unknown-linux-musl
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc
          cargo build --release --package hermes

          export CARGO_BUILD_TARGET=aarch64-unknown-linux-musl
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
          cargo build --release --package hermes

      - name: '[Release] Move Artifacts for Upload'
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd code/target ; mkdir -p .artifacts ;

          mv ../../.assets/x86_64/archive.tar.xz       .artifacts/hermes-${{ github.ref_name }}-x86_64.tar.xz
          mv x86_64-unknown-linux-musl/release/hermes  .artifacts/hermes-${{ github.ref_name }}-x86_64-unknown-linux-musl

          mv ../../.assets/aarch64/archive.tar.xz      .artifacts/hermes-${{ github.ref_name }}-aarch64.tar.xz
          mv aarch64-unknown-linux-musl/release/hermes .artifacts/hermes-${{ github.ref_name }}-aarch64-unknown-linux-musl

      - name: '[Release] Publish Artifacts to Release'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            code/target/.artifacts/hermes-${{ github.ref_name }}-x86_64.tar.xz
            code/target/.artifacts/hermes-${{ github.ref_name }}-x86_64-unknown-linux-musl
            code/target/.artifacts/hermes-${{ github.ref_name }}-aarch64.tar.xz
            code/target/.artifacts/hermes-${{ github.ref_name }}-aarch64-unknown-linux-musl
