---
name: Integration
run-name: Integration

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ code/**, .github/** ]
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ '**' ]
    paths: [ code/**, .github/** ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: docker.io/rust:1.90.0-slim-trixie

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Build-Output
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}-x86_64
          path: code/target/release

      - name: Cache Build-Output
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}-aarch64
          path: code/target/aarch64-unknown-linux-musl/release

      - name: Build and Test
        run: |
            set -e
            cd code

            apt-get --yes --quiet=2 update
            apt-get --yes install binutils-aarch64-linux-gnu gcc gcc-aarch64-linux-gnu musl-tools pkg-config

            export CARGO_BUILD_TARGET=x86_64-unknown-linux-musl
            export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc

            cargo fmt    --all                              -- --check
            cargo clippy --workspace --quiet --all-features -- -D warnings
            cargo doc    --workspace --quiet --no-deps --document-private-items

            cargo run              --package cupid
            cargo build  --release --package hermes

            cargo run --package cupid -- --architecture aarch64

            export CARGO_BUILD_TARGET=aarch64-unknown-linux-musl
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc

            cargo build --release --package hermes

            cp ../.assets/x86_64/archive.tar.xz target/release/
            cp ../.assets/aarch64/archive.tar.xz target/aarch64-unknown-linux-musl/release/

  publish:
    name: Publish
    runs-on: ubuntu-latest

    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Cache for Build-Output (x86_64)
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}-x86_64
          path: code/target/release
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Load Cache for Build-Output (aarch64)
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}-aarch64
          path: code/target/aarch64-unknown-linux-musl/release
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Prepare Binaries
        run: |
          cd code/target
          mv release/hermes release/hermes-${{ github.ref_name }}-x86_64-unknown-linux-musl
          mv release/archive.tar.xz release/hermes-${{ github.ref_name }}.tar.xz
          mv aarch64-unknown-linux-musl/release/hermes \
            aarch64-unknown-linux-musl/release/hermes-${{ github.ref_name }}-aarch64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            code/target/release/hermes-${{ github.ref_name }}-x86_64-unknown-linux-musl
            code/target/release/hermes-${{ github.ref_name }}.tar.xz
            code/target/aarch64-unknown-linux-musl/release/hermes-${{ github.ref_name }}-aarch64-unknown-linux-musl
